import React from 'react';
import Head from 'next/head';
import { Stack, Typography } from '@mui/material';
import Link from 'next/link';
// import index from '../styles/index.module.css';
function Layout({ children, title }) {
  return (
    <>
      <Head>
        <title>{title ? `${title}-QuickHub` : `QuickHub`}</title>
        <meta Autor="pijush ray mondal" content="Devoloper" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack
        direction="column"
        minHeight="100vh"
        justifyContent="space-between"
      >
        <header>
          <Stack
            justifyContent="space-between"
            direction="row"
            p={1}
            alignItems="center"
            sx={{ boxShadow: 3 }}
          >
            <Link href="/">
              <Typography variant="h6" sx={{ fontWeight: 700 }}>
                QuickHub
              </Typography>
            </Link>
            <Stack direction="row" spacing={1}>
              <Link href="/card">
                <Typography>Card</Typography>
              </Link>
              <Link href="/login">
                <Typography>login</Typography>
              </Link>
            </Stack>
          </Stack>
        </header>
        <main>{children}</main>
        <footer>Footer</footer>
      </Stack>
    </>
  );
}

export default Layout;
